function [ coords ] = rotateCoordinates( coords,angleX,angleY,angleZ )
    angleX = deg2rad(angleX);
    angleY = deg2rad(angleY);
    angleZ = deg2rad(angleZ);
    tMatX =[ 1,0,0;...
            0,cos(angleX),-sin(angleX);...
            0,sin(angleX),cos(angleX)];
    tMatY = [cos(angleY),0,sin(angleY);...
            0,1,0;...
            -sin(angleY), 0, cos(angleY)];
    tMatZ = [cos(angleZ),-sin(angleZ),0;...
        sin(angleZ), cos(angleZ),0;...
        0,0,1];
    tMat = tMatX*tMatY*tMatZ;
    coords = coords * tMat;
end